name = "valor-solutions"
main = "worker/index.js"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "valor_solutions_db"
database_name = "valor-solutions-db"
database_id = "db06c879-103f-4087-86f7-374ae10eccaa"
